### ISSUE TITLE
Only scan specific subfolders?

### ISSUE THREAD

**Issue by ghost** [vaeth/bookmarkdupes#111]
fixed

**Comment by vaeth** [comment]
In expert mode, you can create a "filter" rule for bookmarks starting with a specific path.
For example, to avoid scanning rules under "Bookmarks bar | foo.bar", use in the `name matches` field the entry:

```
^Bookmarks bar\0foo\.bar\0
```

Note that symbols from `[].?*()^$` (and probably some more) need to be quoted, and that `\0` denotes the folder separator.

If you use expert mode, please do not forget to switch all other rules to `off` (or to remove them).

**Comment by softlypink** [comment]
Thanks for your reply, Professor. Technology is not my strong suit, so I apologize for not understanding your example. I read the relevant text on Firefox regarding `name matches` but it didn't click for me. Would you mind illustrating it again using the path below, please? Or a shorter path if you prefer.

All Bookmarks > Bookmarks Menu > SocialMedia_Collection > Social Media > Imgur

[Image of my Firefox library](https://i.postimg.cc/053ZKrdX/91b827hjno6.png)

I did search issues before posting, and I read about deactivating all other rules, so that much I know. ;-)
