### ISSUE TITLE
*please* let it show partial search results!

### ISSUE THREAD

**Issue by AlanJayWeiner** [vaeth/bookmarkdupes#28]
I have a butt-ton of bookmarks.  Several times I've switched browsers, importing bookmarks and things end up duplicated.   When bookmarkdupes searches for exact dupes, it takes *forever* (multiple days I suspect) - I have never seen it display the list of duplicate bookmarks!
(I don't know if it's starting a new search when I click 'exact dupes' again...)

Please add a button to stop the search and show the currently-found results!  Then I can delete a lot of the duplicates and search again.

**Comment by jmattlandrum** [comment]
I have a similar issue.  I switched from Chrome to Mozilla and now have many duplicates and many empty folders that can’t be removed with this plugin or manually. I’m wondering if there is some file permanently hosed.

**Comment by AlanJayWeiner** [comment]
I don't have any problem manually deleting or moving bookmarks or folders.
Are you using 'show all bookmarks' (Library) or doing it directly in the
Bookmarks menu?  I've been using the bookmark Library; just tried a
right-click and delete in the Bookmarks menu; that worked also.

Google time, I guess...

**Comment by jmattlandrum** [comment]
I’ve tried deleting from multiple places, in safe mode, etc.  I tried deleting the places.sqlite file.   Firefox hates me.

**Comment by AlanJayWeiner** [comment]
Maybe worth a try - export the bookmarks, create another profile, and import them.  Sounds like something's buggered.

**Comment by jmattlandrum** [comment]
Wanted to try that.  It acts like it is exporting, but no file is written.

**Comment by AlanJayWeiner** [comment]
Something is *very* wrong then.   I've been testing bookmarksdupes and have
both exported and saved-as-html many times.  I save in both forms before
and after I delete things.  Then I diff to verify the changes.   (have not
found any issues there, btw - so far it's only the expected deletions)

I think I'd back up the entire Firefox directory (both the program files
and all the profiles, etc.) and reinstall.  Then try to fiddle the
bookmarks (from the backed-up profile) into the newly-created profile.  I
*think* that's possible, but not sure.

Uh - I'm on Windows 10, btw - what are you on?

**Comment by vaeth** [comment]
> When bookmarkdupes searches for exact dupes, it takes forever (multiple days I suspect)

Unless there is an issue with not enough memory or another strange problem, this should not happen.
The algorithm to find duplicates uses linear time in average (assuming that firefox's java implementation needs in average constant time for hashing in a "Map" object), i.e. if you have the double number of bookmarks, it should only take the double number of time.

How large exactly is the number of bookmarks you have? How large is your memory? (It might help if you close other memory hungry processes.)

How long does it take if you press the button "All bookmarks"?

Here are my test numbers:
For 50000 bookmarks (a copy of 25000 non-duplicate) the button "All bookmarks" needs about 11 seconds while "Exact Dupes" needs about 15 seconds. However, I have 8 Gigabyte of memory which is only used for the firefox process. Lack of memory is a problem which can hardly be solved by the code.

> Please add a button to stop the search and show the currently-found results!

I had experimented with that, but had removed that code again, because it only slowed down.
It turned out that the main time is lost until browser.bookmarks.getTree() finishes (which is browser-internal) and that the actual checking of the obtained tree for duplicates is not much slower than recursing through the full tree. Only this recursing through the tree could be made stoppable, but since javascript is not really multitasking capable, it was necessary for the implementation of the stop button to use a promise in each recursion step. This mechanism alone took longer than parsing through the full tree (and BTW costed a lot of additional memory).

**Comment by AlanJayWeiner** [comment]
Ok, well...  uh...   appears some of the problem is this guy at the
keyboard...

It takes a while to populate the list and for the dialog to show up - long
enough I thought it wasn't working...


Timings are still with 3.0; have to go read up on how to install from git.

All Bookmarks:
First time took 61 seconds.
Clicking away (bookmarkdupes dialog disappears) and clicking bookmarkdupes
again:
dialog becomes large at 0:12, bookmarks displayed at 0:17
repeat:   0:13 and 0:21  (moved mouse at 0:21 and data appears)
repeat:   0:15 and 0:18  (moved mouse as soon as dialog became large, so
data wouldn't be delayed)

Exact Bookmarks:
clicked 'exact bookmarks' button while all bookmarks displayed
took 5+ seconds to close that dialog and display "Searching" - not sure how
long; didn't time it
took approximately 2:19 to display exact bookmarks data
clicking away and back to redisplay dialog:
(first time is when large dialog displayed (empty); second is when
bookmarks data appears)
0:18 and 0:23
0:20 and 0:23
0:24 and 0:27

Empty Folders:
dialog displayed large, immediately displays data at 0:33
had 27 empty folders

clicking away and back - bookmarkdupes dialog displays immediately


Taking 20-25 seconds to display the dialog isn't terrible, although it's
annoying if I click away (e.g., check memory usage...) and have to wait all
over again.


Now, timings for selecting duplicate bookmarks to delete.   These *are*
taking a long time.

With a report of 74761 (of 79935) exact dupes in 21316 groups,
I scrolled down about mid-way, where I had several groups shown, each with
three duplicates in the same folder.  Each was numbered 1, 2, 3.
Starting at the bottom, I clicked on '2', then positioned on '3' and waited
for the checkbox to change color to blue.
Then I'd click it, and move up to the next group, hovering over '2'.
Same process all the way up the groups.

0:00.00            click on '2'
0:04.76   ( 4.76)  click on '3'
0:11.33   ( 6.57)  click on '2' (of next group)
0:21.87   (10.54)  click on '3'
0:32.64   (10.77)  click on '2' (of next group)
0:39.28   ( 6.64)  click on '3'
0:48.35   ( 9.07)  '2'
0:57.03   ( 8.68)  '3'
1:06.93   ( 9.90)  '2'
1:15.75   ( 8.82)  '3'

Thanks for the explanation about the 'stop and show results' button request.

Alan

**Comment by vaeth** [comment]
The problem with changing checkboxes is that I do not want that the state is lost when you close the popup. Unfortunately, this means that the state (i.e. all checkboxes) must be sent to the background process. Firefox is apparently very slow in transferring such huge messages.
Maybe I should spend some time to optimize the sending. Unfortunately, this is very error-prune.

**Comment by vaeth** [comment]
> maybe "delete exact dupes in same exact folder" ?   or "delete exact dupes within each folder" ?

I think this should be solved by 4.0.

> Can it use more of the screen width

Firefox has its own algorithm for selecting the width of popups. I am not sure whether it can be overridden by .css, but even if it is possible I prefer to avoid using css since it will easily break for some users (e.g. with a small screen).

**Comment by AlanJayWeiner** [comment]
Ah, love it when the system does what it wants instead of what you want it
to do...

Haven't had time to install 4.0 yet.  Leaving for family trip tomorrow, so
probably won't have time to try it until Wednesday.

Alan

**Comment by AlanJayWeiner** [comment]
>
> The problem with changing checkboxes is that I do not want that the state
> is lost when you close the popup. Unfortunately, this means that the state
> (i.e. all checkboxes) must be sent to the background process. Firefox is
> apparently very slow in transferring such huge messages.
> Maybe I should spend some time to optimize the sending. Unfortunately,
> this is very error-prune.


Nah - I'm an edge case.   Let me see if I can delete lots of same-folder
duplicates when I get 4.0.  I'm guessing it's so slow because I've got so
many duplicates.

Alan

**Comment by perdolka** [comment]
> The problem with changing checkboxes is that I do not want that the state is lost when you close the popup. Unfortunately, this means that the state (i.e. all checkboxes) must be sent to the background process. Firefox is apparently very slow in transferring such huge messages.
> Maybe I should spend some time to optimize the sending. Unfortunately, this is very error-prune.

What happens if you replace popup to a new window or tab (theoretically)?
Firefox will also be slow because of this?

**Comment by vaeth** [comment]
> What happens if you replace popup to a new window or tab (theoretically)?

It's the same problem if you want that the window's state is restored after reopening.
(Of course, for a window/tab this is not so much necessary as for a popup.)
In any case, using a window would be a rather different program which would need additional permissions.

I think the problem with sending less data is much easier to solve; it is actually not really hard, but one has to be very careful with races. It is mainly a question of finding some time for coding. In the moment, there are things in my life which are much more important.

**Comment by AlanJayWeiner** [comment]
Having it pop up in a tab would be great.  (I assume selecting bookmarks
would be as fast as a normal web page...)   However - what happens if I
change bookmarks in the library; will the tab be out of date and try to
delete entries that don't exist or have changed - will it delete the wrong
bookmarks?

Martin - definitely!  Life is more important than coding.   Not by much,
but still...   :)

(I'm packing a small screen, keyboard, mouse, Raspberry Pi (maybe several),
network cables, etc for Christmas family time.  They're used to it - one
time I shipped a whole Sun workstation to my in-laws.   :)

**Comment by vaeth** [comment]
The current version in the master branch now opens in a tab instead of a panel.

In the moment, this means essentially just an optical change; the functionality is the same, i.e., if you close the tab and re-open it, the old content will be re-displayed (including your markings).
To save memory and time for transferring, this functionality would have to change.

There is in the moment just one functional/speed improvement: The bookmarks are now tabs, and you can click and switch to them without having to re-open a panel (which took time if you had many bookmarks).

**Comment by vaeth** [comment]
The background process is now eliminated, so things should be much quicker now and need less memory.

This is almost a complete rewrite, so lots of new bugs might have arisen.

Careful testing is needed before releasing ;)

**Comment by AlanJayWeiner** [comment]
Hi Martin!
You've been busy!  (Thank you!)

I like the tab much better.  I could select bookmarks to be removed very
quickly.  Slight delay, but nothing to complain about.  (I suspect normal
people with only a handful of duplicates won't see any delay at all)

I loaded All Bookmarks several times; times were:  46 seconds the first
time, second time the "select a folder" message displayed at 57 seconds;
the bookmarks displayed about 10 seconds later.  Third time took 58 seconds.

Selecting 'display URL' updated the page in about 11 seconds.

Empty folders took 37 seconds, and displayed 5 empty folders.

Exact dupes took 59 seconds to display - nice!
74310 (of 79693) exact dupes in 21179 groups.

I deleted 10 bookmarks in 5 groups.  Save the bookmarks before and after;
compared them and everything looks right.
Deleted another 6 - again everything good.

I think it's much easier to use in the tab - selections are very quick.

Al

**Comment by vaeth** [comment]
Thanks for the testing.

Concerning the delay: I hoped that counting all boxes after every checkbox change is quick enough.
I recoded it now by hashing the marked boxes: Faster, but higher memory requirements.

**Comment by AlanJayWeiner** [comment]
Can't tell if the checkboxes are faster or not - they're almost instant
some times, occasionally a short delay (2-3 seconds subjective).  But
that's with my absurd number of duplicates...   Showing 7 groups of 3
bookmarks each, selecting #2 and #3 in each group - first one is immediate,
then slight delay.  By the time I've selected the 14, there's a 2-3 second
(?) delay before they all show the checks.  Only problem (*very* minor) is
sometimes I'll miss the checkbox so it doesn't get selected; I won't know
that for a moment.  Really not a big deal.

I selected 25 bookmarks that were scattered randomly, some in groups with
other dupes (so group will persist). In 3 groups I selected all the
bookmarks,
Diffed before and after; everything was just as expected.  25 bookmarks
removed, all matched the selections.

I'll do some bigger deletions later...

Timings:

All bookmarks 1:06  (was a bit faster before; could easily be other things
going on in the notebook - haven't been rigid about that)
Empty folders 0:44 (also a bit slower) with 5 empty folders
Exact dupes 1:11
74286 (in 79677) in 21171 groups.   (before removing the 25)

Looks good!

There's visual stuff that could be improved (always in my less-than-humble
opinion!) - I'll write some thoughts later.   Gotta go help with cooking in
a moment.

Al

**Comment by vaeth** [comment]
I would like to release 4.0 as quickly as possible when it does not contain a serious bug anymore:

> sometimes I'll miss the checkbox so it doesn't get selected

This sounds serious.

Do you mean: You press "mark all but youngest" (or which button precisely?) and only a subset of the bookmarks will be marked? This would mean a serious bug in the algorithm for that button.

Or do you mean: You press a checkbox and it doesn't get marked?

If this happens, I think it is a firefox issue. The only other possibility is that you pressed some of the buttons (like "mark all but youngest") and tried to check the box before that operation was finished.
Yes, I am aware that boxes should be disabled until the operation is finished, but I am hesitating to do this, because disabling/re-enabling thousands of checkboxes might take a ridiculous amount of time.

> But that's with my absurd number of duplicates...

This shouldn't have any influence concerning the code of the extension: All that is happening in the extension is that a bookmark is removed/added to the hash table, and the number is updated. These actions are independent of the number of displayed bookmarks.

Of course, the updating of the number might cause some delay on firefox if the displayed page is huge.

I thought about adding a checkbox to make the display of selected numbers optional, but I am not yet decided: This might be rather confusing to the users.

**Comment by vaeth** [comment]
In the master branch both is implemented:

1. There is a checkbox to disable counting
2. Bookmark checkboxes are disabled during updating of checkboxes

I hope that using ```setTimeout()``` will force the disabling to happen before the marking algorithm gets executed: I found no official documentation that setTimeout() will force this, although it _seems_ to work.

**Comment by vaeth** [comment]
Since bookmarkdupes-4.0 is now released, I am closing this bug.
Feel free to open another one if e.g. you have further suggestions.
