### ISSUE TITLE
options

### ISSUE THREAD

**Issue by perdolka** [vaeth/bookmarkdupes#32]
>     Unmark all from “$TITLE$
>     In groups containing “$TITLE$” mark all but these
>     Mark all from “$TITLE$”
>     In groups with “$TITLE$” mark only these

Maybe it makes sense to hide these 12 new buttons by default?
E.g. make them available in the addon options by clicking on the checkbox.

**Comment by vaeth** [comment]
Great idea!
Now that there is a folder selector (instead of two rows of buttons for categories), it is natural to select an folder by default and let the corresponding buttons appear only when a folder is selected.
Already pushed to master

**Comment by perdolka** [comment]
"selected folder" - no need to translate?

**Comment by vaeth** [comment]
I cannot translate into Russian or Ukrainian.
In cases like this - when the text is only slightly changed - there are 3 possibilities:

1. I can either write the new text only in English and completely rely on translators.
2. I try to add/modify English phrases where I guess that they belong.
3. I could leave the old translation

I think 3 is a bad choice, since it provides wrong/outdated information until the translation happened. (In the current example, it might perhaps even break, since the new text does not have any arguments).

The result of 2. is of course a horrible mixture of languages. But the advantage is that it might perhaps be understood by some native speaker who hardly speaks English (think of the case that a translator quits; e.g. currently the Chinese translation is still very outdated). Another advantage might be that it is simpler for translators, because you do not have to re-translate a sentence which you have already "almost" translated. (Of course, also in case 1. I could have put the old translation into a comment.)

On the other hand, 1. would be much less work for me, and people familiar with English will not be annoyed by a mixture of languages.

I was not sure how to deal with the situation, so I opted for 2.

**Comment by perdolka** [comment]
I mean, "selected folder" is untranslatable piece of code, like “$TITLE$” ?

Those strings, where you just replace “$TITLE$” to "selected folder" (uk and ru) - everything is correct, so I can use that as is.

**Comment by vaeth** [comment]
No. These "placeholders" always have the form $FOO$ or $number, and they require a "placeholder" entry in the translation.

**Comment by perdolka** [comment]
OK, I'll translate it later.
