### ISSUE TITLE
Suggestion for other types of "similar bookmarks"

### ISSUE THREAD

**Issue by Valeryan24** [vaeth/bookmarkdupes#45]
Hello,

First best wishes for 2018 and thanks a lot for your great work and your extension Bookmarks Dupes which is very useful : I wait since years that a developer (I don't know coding myself) adds a feature to detect similar bookmarks, not only exact dupes (I manage more than 12.000 bookmarks with lots of them to sort).

And version 4.2 improves a lot the design !

I have some suggestions and needs regarding the "similar" function, if it is possible to add them, and of course if you find it suitable :

I have many "duplicates" which do not have exactly the same URL but are the same page, or just another page of the same site, not detected by the extension because the different links don't have the "?" inside ; so Bookmark Dupes could also verify :

    Bookmarks similar with https SSL encryption :
    http://www.xxxxx.com
    https://www.xxxxx.com

    Bookmarks similar with or without www or ww2... :
    http://www.xxxxx.com
    http://ww2.xxxxx.com
    http://xxxxx.com

    Bookmarks with sub-domain (other characters before main domain), with or without www :
    http://www.yyy.xxxxx.com
    http://yyy.xxxxx.com
    http://xxxxx.com

    Combination of SSL and no www :
    https://www.xxxxx.com
    http://xxxxx.com

    Bookmarks similar with or without / at the end :
    http://www.xxxxx.com
    http://www.xxxxx.com/

    Bookmarks similar with same domain but different addresses :
    http://www.xxxxx.com
    http://www.xxxxx.com/index.html
    http://www.xxxxx.com/article1.htm
    http://www.xxxxx.com/forum.php/p=1&sid=zzzzzzzzzzz

Results would be displayed in addition to Duplicates in the "Similar" screen, like now with the parent folder, possibility to compare and suppress one (some) of them - because sometimes I want to have the main page of a site and also a sub-page as two separate bookmarks, and sometimes not : it's just a duplicate.

With **option to whitelist some domains :** because sometimes there are plenty of sites on a same main domain (wordpress.com ; github.com ; youtube.com ...) but they are all well different and the results list would be too long with them.

Is it an idea which seems you interesting ? I'd like to help but don't know any programming, I tried to look on the source code without understanding how to do this, but I can made a donation...

Thanks in advance. Best regards,

Xavier

**Comment by vaeth** [comment]
I will reply in some days (some personal duties...).

**Comment by vaeth** [comment]
Today I found some time for coding.

The new version 5.0 (on master branch) now has a rather configurable way to define dupes and to filter bookmarks. You can get with it everything you requested, but you have to be familiar with regular expressions to configure it. That's why it is now hidden as an "expert option". Although I hope that it is understandable without any instructions (if you know regular expressions), the new README.md5 (on github's main page for bookmark dupes) describes some details and gives references where you can read about regular expressions.

This option now covers also the differences between "exact" matches and "similar" matches, so it is no longer necessary to have 2 buttons.

> donation...

Maybe I should setup some account and button... I will post here again when I do. ;)

**Comment by Valeryan24** [comment]
Hi, thanks a lot for the answer and the quick good work !
I tested the updated 5.2 version, not thoroughly for the moment (there are many welcomed options to select, I just ran the expert mode without changing anything), it seems to work very fine and it already detected about 20 similar bookmarks that I did not see before.
Addon definitively adopted for me and waiting for the donation button :)
