### ISSUE TITLE
A few remarks.

### ISSUE THREAD

**Issue by perdolka** [vaeth/bookmarkdupes#52]
- [x]  Graphic buttons "Insert a new rule." looks like a "Delete" or "Close".
I propose to replace it with "**+**".

- [ ] Perhaps, it makes sense to use one "Insert a new rule." button instead of a few.

- [ ] When the radio button "**Filter**" is enabled, all parameters of radio button "**Modify**" are blocked.
So, it may also make sense to block "**Filter**" parameters when the radio button "**Modify**" is active ?
Anyway, a "Filter" parameters doesn't work when "Modify" button is active.

- [x]  Now, I'm trying to fix my translations more carefully, by modifying a Options page (saved html).
In this connection, I have a request - can I try to use **Alt+255** blank space in some names of the buttons - for more precise alignment of the tables?
I really like the result.

**Before:**
<a href="http://piccy.info/view3/11992754/928dcad1c6c24b05387a00fccf4977cb/1200/" target="_blank"><img src="http://i.piccy.info/i9/72f5df24038c925715e3a6363d55f311/1516748330/38237/1207467/before_800.jpg" alt="Piccy.info - Free Image Hosting" border="0" /></a><a href="http://i.piccy.info/a3c/2018-01-23-22-58/i9-11992754/800x217-r" target="_blank"><img src="http://i.piccy.info/a3/2018-01-23-22-58/i9-11992754/800x217-r/i.gif" alt="" border="0" /></a>
**After:**
<a href="http://piccy.info/view3/11992757/bee42bb5a6ae07ab524cabc4470a86d4/1200/" target="_blank"><img src="http://i.piccy.info/i9/cd06a58d0619f97707cd00d85176d534/1516748384/28456/1207467/after_800.jpg" alt="Piccy.info - Free Image Hosting" border="0" /></a><a href="http://i.piccy.info/a3c/2018-01-23-22-59/i9-11992757/800x217-r" target="_blank"><img src="http://i.piccy.info/a3/2018-01-23-22-59/i9-11992757/800x217-r/i.gif" alt="" border="0" /></a>

**Comment by vaeth** [comment]
> Graphic buttons "Insert a new rule." looks like a "Delete" or "Close".

The idea was that it is an "inverted" delete.
But you are right that a + is much more intuitive. I will temporarily change this in all translations

> Perhaps, it makes sense to use one "Insert a new rule." button instead of a few.

The problem is that location of the rule matters. In the beginning this was important, because there were no "move up/down" buttons.
You are right: As long as the rule list is not too long, the "+" button could be replaced by a single "+" button in the first line which inserts a new rule e.g. at the beginning; then the user would "just" have to press "+" and then several times the appropriated "down" button.
However, if the list is long, this might be inconvenient. Since the "new" button is the last button in the row anyway and thus is not disturbing even on a small screen, I am hesitating to remove it.

> When the radio button "Filter" is enabled, all parameters of radio button "Modify" are blocked

If a "Filter" rule applies, the corresponding bookmark will be ignored: It makes no sense to interpret its URL differently or to apply further rules to it, because the whole bookmark is considered as "nonexistent" for all main actions ("dupes", "empty folders", "all bookmarks") of the extension.
In this sense, a "filter" rule is a completely different thing than a "modify" rule, although optically they look similar, because the criteria to apply them are the same.
And depending since these criteria involve the URL, the user might want to apply a certain filter rule before or after certain URL modifier rules: That's why they are not shown in a separate table but just appear "in between" the other rules. This is not ideal from the viewpoint of intuition but good from the viewpoint of functionality.

> by modifying a Options page (saved html)

What is "saved html"?

> Alt+255 blank space

It depends on your editor what this is. If you are speaking about unicode non-breakable space (U+00A0) then it should be fine to use it in translations. However, be aware that people might use different fonts or font sizes, so you cannot rely on a certain "size" of the titles in the table.
If the purpose is to generate some space after the 6th and 8th table cell, then I should better put this into the table code. However, I am a bit hesitating to waste space "unnecessarily", because the length of a table line is already a problem on monitors with a small resolution.

A solution to this space problem might be to decrease the size of cells, but it looks rather disturbing if the cells have different sizes, and the "table titles" need a certain minimal size anyway (and I don't know how to force breaking the "table titles" into several lines; even if I would know, I am not sure whether this would be a good idea.)

Anyway, perhaps a few points of space between the cells do not matter too much.

**Comment by vaeth** [comment]
In the current master branch, I added space after the 6th and 8th table cell, so it should no longer be necessary to add unbreakable space in any translation.

If you want to add unbreakable space for another reason, it is perhaps better to use the explicit \xa0, so that it is clearly displayed in any editor.

I also changed now all translations to use the heavy plus sign for generating a new rule.

Finally, I replaced the pictograms in all translations by verbose \U+... codes so that there is no problem with editors which possibly do not handle UTF8 correctly. In particular, this makes sure that the pictograms are easy to use consistently in all translations. For instance, the heavy plus sign (which is used now for "new rule") and the heavy greek cross (which I had used in one commit by mistake when I did not look up the unicode rules) look the same in many editors/fonts, but if the user has a font where they differ, it would be strange if one would be used in spanish while another is used in russian (e.g.).

**Comment by vaeth** [comment]
> Now, I'm trying to fix my translations more carefully

Did I understand correctly that some translation updates are almost finished?
I am planning to make a 5.1 release due to the Spanish translations. It would also contain the extra space in the table you mention.
If further translations are to be expected soon, I would still wait a bit...

**Comment by perdolka** [comment]
Yes, I finished.

**Comment by vaeth** [comment]
> Yes, I finished

Great! Thanks! I will release ASAP.
