### ISSUE TITLE
folder deduplication takes SEVERAL stages to execute, seem to delete non-empty directories too

### ISSUE THREAD

**Issue by PeeTeeH** [vaeth/bookmarkdupes#70]
I try to merge my updated bookmarks between Firefox Pale Moon and Firefox Quantum.
I exported my bookmarks in HTML format from Pale Moon 27.8.1.
I imported them in Firefox 59.0.1.
(both browsers contain about 2,5k bookmarks)
I used de-dupe with option (delete all but oldest). It removed the dupes.
Then I used action to search for empty dirs. 
It deleted some. I searched for empty dirs again. It deleted some. And again. And again.
See screenshots in unlisted IMGUR gallery.
https://imgur.com/a/Xm7MB
What info can help you isolate the issue?

**Comment by vaeth** [comment]
According to the screenshots, the “problem” in your case seems to be that you had folders which contained nothing but folders. Such folders are not considered to be empty!
They become empty only in the moment when the empty folders inside are removed.
Since apparently you had several levels of empty folders stacked inside each other, you needed several iterations to remove them all.

The alternative what the extension could do is to consider folders as empty even if they contain empty folders (which in turn might contain empty folders etc). This would solve your problem of requiring several iterations, but it would be dangerous, because not every user would consider such folders as empty: He might loose a carefully designed folder hierarchy only because inside that hierarchy there is currently no bookmark stored.

So more or less bookmarkdupes only has the alternative to make one of the two type of users unhappy. When in doubt, I consider it better to keep something than to remove it. The price you have to pay is that you might have to repeated the “remove empty folders” step up to the height of your current folder tree when you want to remove also all folders containing only empty folders.

**Comment by PeeTeeH** [comment]
I did some changes to bookmark tree on both browser platforms so after merge and de-duplication it might result in multiple nested empty dirs.
Thanks for your valuable feedback!
