### ISSUE TITLE
Folder aren't considered empty if they contains "Separators"

### ISSUE THREAD

**Issue by TheFrenchGhosty** [vaeth/bookmarkdupes#85]
"Empty Folders" doesn't consider folders empty is they contain one or more "Separator".

It would be nice if "Separators" were considered as "nothing" since they exist only to provide an enhancement to the UX.

**Comment by vaeth** [comment]
This would imply to actively remove separators which the user at some time has added manually. This appears too intrusive to me.

**Comment by TheFrenchGhosty** [comment]
Well the thing is that separators are meant to "organize" bookmarks, having them without the bookmarks is useless, so I really don't see any point in keeping them.

**Comment by vaeth** [comment]
Yes, I understand. However, they were created intentionally by the user, so they should also be removed only intentionally and not tacitly “on the fly”. Perhaps they were even created in order to keep tools like bookmark dupes from considering the folders as empty. Only thing I could imagine would be to create an enhanced UI which would display them and allows them for being marked for deletion, but IMHO this complexity is overkill.

**Comment by PAI5REECHO** [comment]
Here's something for consideration: If you have say 3,000 bookmarks with 300 folders, each containing many separators and you happen to import the bookmarks twice by accident you now have duplicates. Once you've removed the duplicates, 300 folders will now be left, as they're not empty and contain separators. You'd have go and manually identify the empty folders containing separators which is very tedious if they're intermixed in random locations for some reason. A feature to simply filter for `Empty folders (ignoring separators)` instead of `Empty folders` would solve this problem, it's definitely not overkill. Anyways since this extension lets you first stage what you want to delete before actually deleting it this would be a quite safe/non-destructive and convenient feature to save time for scenarios like I described.
