### ISSUE TITLE
method of selection bookmarks

### ISSUE THREAD

**Issue by perdolka** [vaeth/bookmarkdupes#9]
I propose to change the method of selection bookmarks, if it's possible.

from
**Mark all but first in each group** (by position in list)
to 
Mark all except first in each group - by time of adding (i.e. except one, oldest bookmark)

from
**Mark all but last in each group** (by position in list)
to 
Mark all except last in each group - by time of adding (i.e. except one, newest bookmark)

**Comment by vaeth** [comment]
Unfortunately, stripping of comments changes the time of adding (because as mentioned in issue #8 it happens by the trick that a new bookmark is added and then the old removed). So far, I did not consider this a serious problem and therefore did not mention it anywhere, but if there are buttons like
**mark all but youngest in each group**
**mark all but oldest in each group**
this becomes an issue. Anyway, I like the idea, but I would add these buttons _in addition_ (and not _instead_) of the current buttons. Let's see when I will find time for coding...

**Comment by vaeth** [comment]
I the master branch, the age is now indicated by numbers, and the mentioned 2 buttons are added.

**Comment by ofsahin** [comment]
Hello, an issue i encountered is this:
I have almost half of my bookmarks as dupes. somehow lots of them ended up copied to an unsorted bookmarks folder. Also, I cannot use mark youngest and oldest in each group options because some of the bookmarks are oldest but in the wrong folder, some of the bookmarks are youngest but also in the wrong folder.

would it be possible to prioritize bookmarks in certain folders for deletion or for keeping?

[https://i.hizliresim.com/NOQjng.png]
1) bookmarks in the toolbar are more organized then bookmarks in the menu and should be kept.
2) but at the same time 1unsorted bookmarks are not prioritized and should be deleted.
these two objectives cannot be achieved with the current setup

another idea:
extension, normally, lists all dupes, after selection the list is still the same length. you have to scroll through all the bookmarks to check them. marked bookmarks could be invisible in order to make it easy to go through unmarked bookmark groups.

for your consideration.
thank you for the extension.

**Comment by vaeth** [comment]
I added now further buttons for marking/unmarking all bookmarks from a category.
Here, a category is a top-level bookmark folder; usually "bookmark menu" and "bookmark toolbar" are the only categories.
In addition "mark all" is now also shown in the listing of duplicate bookmarks.

This does not achieve directly what you suggested, but e.g. you can easily exclude bookmarks from the bookmarks menu from deletion. Then you can remove the remaining duplicates and recalculate the list.

Hiding bookmarks in some cases is not a good idea IMHO: If not all information is shown, the interface would no longer be transparent but rather confusing.

**Comment by vaeth** [comment]
I added now yet further buttons to marking/umarking all other bookmarks in a groups except for the specified category.

Now you can probably achieve what you wanted in several steps.

It is still not possible to use all reasonable combinations directly (e.g. "mark in each group all except one with a specified order of preferences"), and I am afraid that all attempts to provide them will be too complex to be usable in an UI.

If you have an idea and prove me wrong, I would be happy ;)

**Comment by perdolka** [comment]
> "example" - These strings (labeled as // new) also need to be translated?

To be honest: I don't know when these "example" values are ever used; I just saw them in all examples of localization files with parameters, so I suppose that they have to be there and are perhaps used in some environments (perhaps in some editors which support editing these files…).

Probably it does not hurt if they are not translated, except that it might be misleading for future translators: The value actually inserted for the argument is localized, of course. Since there are essentially only two cases (copied several times), I thought that it does not hurt to indicate that they might deserve a translation...

**Comment by perdolka** [comment]
Maybe I'm doing it wrong. 
Isn't that the same result in both ways?

**Unmark all from “$TITLE$**
vs
**In groups containing “$TITLE$” mark all but these**

and

**Mark all from “$TITLE$”**
vs
**In groups with “$TITLE$” mark only these**

**Comment by vaeth** [comment]
The second always does more than the former:
**In groups containing “$TITLE$” mark all but these**
means not only that all from “$TITLE$” are unmarked but also that all others (in the corresponding groups) are marked. (Actually, I think that it is not clear from the formulation that all bookmarks from $TITLE$ are unmarked; but with a verbose explanation the button text would be horribly long; that's why this is explained in the title (tooltip) text)

Similarly,
**In groups with “$TITLE$” mark only these**
means not only that all from “$TITLE$” are marked but also that all others (in the corresponding groups) are unmarked. (Again, the latter is explained only in the title text of the button.)

**Comment by perdolka** [comment]
Maybe it makes sense to hide these 12 new buttons by default? 
E.g. make them available in the addon options by clicking on the checkbox.

**Comment by ofsahin** [comment]
Hello,

first of all thank you for your time.
i just tried the new version with all these confusing and useful buttons :) and it works. in 4 passes i managed to weed-out duplicates.
