### ISSUE TITLE
"Remove Marked Bookmarks" button missing in "All Bookmarks" view

### ISSUE THREAD

**Issue by zounp** [vaeth/bookmarkdupes#95]
Thanks for this nice extension.
When I wanted to delete some marked bookmarks in the "All Bookmarks" view I could not find a button "Remove Marked Bookmarks" . Maybe I overlooked it otherwise would it be nice if there is a "Remove Marked Bookmarks" in the "All Bookmarks" view.
Thanks.

**Comment by vaeth** [comment]
Thank you for your suggestion.
However, the "All Bookmarks" view was meant to serve only for stripping descriptions.
Sooner or later this button will be removed completely, once firefox does this automatically.

Adding a remove button in this section would be very misleading; already now the remove button in the non-dupe section is questionable (people already got bitten by it).

Regular removing should better be done over the built-in bookmark editor.

**Comment by zounp** [comment]
Yes, people can get bitten by it. Bookmark dupes is a dangerous extension. So people who don't want to take the risk f being bitten by it shouldn't use it in the first place I think.
Also it might be a good idea to make a backup of the bookmarks sqlite file before using Bookmark dupes.

I do not understand, why descriptions need to be removed. I useded them until Mozilla removed the bookmark descriptionbox whitout any notice.

The big advantage of Bookmark dupes over the built-in bookmark editor is that I can see the location of the bookmarks in the direcory tree. That is not shown in the built-in bookmark editor. Bookmarkdupes is the only extension that can show paths as far as I know.

Regular removing in the built-in bookmark editor is therby not practical since I can not see where a bookmark is located. That make the built-in bookmark editor rather useless for me.

The advantage of hte All Bookmarks view is that I can see what other bookmarks there are in a direcory combined with the path. Then I can remove the ones I do not need if there was a button :-).
The Dupes view can do the same for duplicate bookmarks. Although the All Bookmarks view is also useful as I wrote above.

Thanks
--
With kind regards,
Zounp
‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by vaeth** [comment]
> shouldn't use it in the first place

But they do. And if it claims to remove all duplicates but then removes all bookmarks due to a misunderstanding, they complain.

> I do not understand, why descriptions need to be removed.

They used to be filled by some content of the website. For most websites, this could be considered as spam. Anyway, as mentioned, firefox already does no longer support descriptions, although they are not yet removed (e.g. if you export bookmarks). Once they are removed by firefox, this is feature no longer needed, and so the "all bookmark" view will be gone.

For your purpose the "No duplicates" view should be almost as good: Instead of one list you only have two (together with the "duplicates" view which you can also use to delete every bookmark).

**Comment by zounp** [comment]
Thanks for the explanations :-)
I will manage :-)
Thanks for the nice extension.
